// Lucide icons (web/control/lucide-icons.js, generated by scripts/control-ui-lucide.mjs), built with
// createElementNS from that static table. Callers pass a key only — never markup — so the render
// boundary holds.
import { LUCIDE } from './lucide-icons.js';

const NS = 'http://www.w3.org/2000/svg';
const STROKE = '1.6'; // the weight the operator picked on the samples page
const warned = new Set();

export function icon(name, { size = 18, label } = {}) {
  const svg = document.createElementNS(NS, 'svg');
  svg.setAttribute('viewBox', '0 0 24 24');
  svg.setAttribute('width', String(size));
  svg.setAttribute('height', String(size));
  svg.setAttribute('fill', 'none');
  svg.setAttribute('stroke', 'currentColor');
  svg.setAttribute('stroke-width', STROKE);
  svg.setAttribute('stroke-linecap', 'round');
  svg.setAttribute('stroke-linejoin', 'round');
  svg.classList.add('icon');
  if (label) {
    svg.setAttribute('role', 'img');
    svg.setAttribute('aria-label', label);
  } else {
    svg.setAttribute('aria-hidden', 'true');
  }
  let parts = LUCIDE[name];
  if (!parts) {
    // A missing name shows a question mark, never a look-alike icon.
    if (!warned.has(name)) { warned.add(name); console.warn(`icon: no "${name}" in lucide-icons.js`); }
    parts = LUCIDE['circle-help'];
  }
  for (const [tag, attrs] of parts) {
    const el = document.createElementNS(NS, tag);
    for (const [k, v] of Object.entries(attrs)) el.setAttribute(k, v);
    svg.append(el);
  }
  return svg;
}
